Sprint1/step2
FabioTw/react-burger pull request #2
Opened 2022-02-09 12:11 UTC by FabioTw

2022-02-09 13:55 UTC, ChrisGerBy requested changes
Здравствуйте!
Вы проделали большую работу:
- познакомились с react portal и применили на практике;
- написали множество функциональных компонентов, в которых использовали хуки useState и useEffect;
- реализовали запрос к api за данными.

Однако, есть несколько существенных замечаний, которые необходимо принять во внимание, чтобы двигаться дальше:
- несоответствие некоторых частей приложения дизайну;
- неверная функциональность приложения при клике на ингредиент;
- неверная функциональность приложения при клике на иконку удаления ингредиента из конструктора;
- не реализовано закрытие модалки при клике на ModalOverlay и при нажатии на клавишу Esc;
- в некоторых файлах компонентов создано несколько компонентов, а должен быть один файл - один компонент, поэтому нужно вынести все вспомогательные компоненты в директорию src/components;
- в некоторых компонентах не описаны propTypes, для типа array не описана структура.

Из того, что можно улучшить:
- именование функция, пропсов, переменных (см. подробные комментарии по коду);
- есть, вероятно, излишние итерации по массиву, которых можно избежать, чем Вы сможете оптимизировать код;
- итерации по массиву методом map всегда возвращает новый массив, поэтому внутри array.map всегда должен быть return. Изучите также методы reduce, filter, forEach, чтобы понимать разницу между ними и использовать верный метод для достижения различных целей.
 

Успехов в рефакторинге кода!

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
>    array.map((item) => {
**Надо исправить**
неверное использование метода map для массива. Map всегда возвращает новый массив, поэтому ожидается, что колбэк будет иметь return.
Ваша цель в этой части кода - пройти по массиву и сделать какие-то действия для внешнего массива correct. Для прохода по массиву без создания нового массива следует использовать метод forEach. Кроме того, Вам следует изучить другие методы массива, которые даже лучше подходят для достижения Вашей цели (filter, reduce, например).

Также стоит задуматься об оптимальности кода: зачем передавать _id в ElementCreator, если он может быть неправильным и делать какую-то дополнительную проверку. Стоит задуматься о том, как сделать так, чтобы передаваемые данные были уже сразу правильными и избежать подобных проверок.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    })
**Надо исправить**
неверное применение метода map для массива: см. комментарий к 54 строке этого файла.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>    });
**Надо исправить**
неверное применение метода map для массива: см. комментарий к 54 строке файла BurgerConstructor.jsx.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/Modal/Modal.jsx
> +import PropTypes from "prop-types";
 **Надо исправить**
неиспользуемый в этом файле импорт PropTypes.

Пожалуйста, допишите propTypes для всех передаваемых в компоненту Modal пропсов.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/ModalOverlay/ModalOverlay.jsx
> +import PropTypes from "prop-types";
**Надо исправить**
неиспользуемый в этом файле импорт PropTypes.

Пожалуйста, допишите propTypes для всех передаваемых в компоненту ModalOverlay пропсов.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/ModalOverlay/ModalOverlay.jsx
> +}
**Надо исправить** 
добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.
<img width="234" alt="image" src="https://user-images.githubusercontent.com/45519864/153203875-097a02c7-487a-4426-abf0-6ce76c36a733.png">

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/ModalOverlay/modal-overlay.module.css
> +}
**Надо исправить** 
добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.
<img width="141" alt="image" src="https://user-images.githubusercontent.com/45519864/153203937-66955135-f6e6-42e2-bdaa-0a520b58a538.png">

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/OrderDetails/OrderDetails.jsx
> +}
**Надо исправить** 
добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.
<img width="167" alt="image" src="https://user-images.githubusercontent.com/45519864/153203993-9cb74899-2018-4c93-9bee-84fc8e65385b.png">

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/App/App.jsx
> +  const [ingridients, addIngridients] = React.useState([])
**Надо исправить**
во всех компонентах, где используете слово ingredients, исправьте, пожалуйста, правописание (не `ingridients`, а правильно `ingredients`

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +const ElementCreator = ({ array, _id, isTop, deleteThis, updateIngredientOverlay, updateIngredientItem }) => {
**Надо исправить**
из файла компонента экспортируется, как правило, один компонент (файл BurgerConstructor должен содержать функцию/класс с компонентом BurgerConstructor). Поэтому если Вам нужен вспомогательный компонент ElementCreator, вынесите, пожалуйста, его в src/components/ElementCreator.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +}
**Надо исправить**
Вы в саму функцию передаете 2 функции, которые нужно вызвать и аргумент для одной из функций.
Таким образом Вы из самого верхнего компонента App передаете ссылки на функции, которые нужно вызвать. А все для того, чтобы получить item, по которому кликнул пользователь. 
Рекомендую попробовать сделать рефакторинг:
- в компоненте App создать функцию showIngredientDetailsModal, например, которая будет передаваться в BurgerConstructor  и в качестве аргумента принимать item.
- внутри этой функции Вы сделаете два необходимых действия, согласно Вашему, коду `updateOrderOverlay` и `updateIngredientItem`;
- внутри BurgerContructor компонента Вам необходимо принять и описать пропсу showIngredientDetailsModal;
- далее Вы можете передать эту пропсу в ElementCreator и в ней уже вызывать ее, как onClick с аргументом item ЛИБО передать в ElementCreator пропсу onClickElement={() => showIngredientDetailsModal(item) } - на стадии передачи пропсы в ElementCreator у Вас уже есть item, потому что Вы его и передаете внутрь ElementCreator.

Таким образом Вы:
- избавляетесь от `selectIngredient`;
- убираете из BurgerConstructor 2 лишние пропсы (BurgerConstructor компоненте не нужно знать о `updateOrderOverlay` и `updateIngredientItem`, этой компоненте Важно лишь знать о showIngredientDetailsModal - а как это будет делать App, BurgerConstructor-у все равно).

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  _id: PropTypes.any.isRequired,
**Надо исправить**
фактически _id не соответствует типу any, у него есть вполне конкретный тип, который можно описать точно. Старайтесь, не использовать any для описания propTypes.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +const Card = ({id, img, price, text, update }) => {
**Надо исправить**
один файл - один компонент. Вынесите, пожалуйста, все вспомогательные компоненты в src/components.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +          <CardList array={ingredientsInfo} update={updateBun} find="bun" />
**Надо исправить**
find - это глагол, который описывает ДЕЙСТВИЕ. Таким образом называют, как правило, функции, а не строки. Вам следует переименовать передаваемую пропсу, чтобы она точнее описывала то, что в ней передается (в данном случае это должно быть существительное).

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  }
**Надо исправить**
название функции неверно описывает ее действие. Имя функции должно отражать то, что она фактически делает. Переименуйте, пожалуйста.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/IngredientDetails/IngredientDetails.jsx
> +export const IngredientDetails = ({updateIngredientOverlay, name, image, proteins, fat, carbohydrates, calories}) => {
**Надо исправить**
добавьте, пожалуйста, описание propTypes для передаваемых пропсов.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/IngredientDetails/IngredientDetails.jsx
> +}
**Надо исправить** 
добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.
<img width="143" alt="image" src="https://user-images.githubusercontent.com/45519864/153208294-d4a15570-0e00-45fe-8c3c-7609dd27e72f.png">

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/IngredientDetails/ingredient-details.module.css
> +}
**Надо исправить** 
добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.
<img width="154" alt="image" src="https://user-images.githubusercontent.com/45519864/153208362-6013c941-1ebf-4c82-a78f-2e0f3bad18cb.png">

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/Modal/modal.module.css
> +}
**Надо исправить**
 добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.
<img width="186" alt="image" src="https://user-images.githubusercontent.com/45519864/153208425-d48bb479-561e-43af-8a72-115840212105.png">

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/OrderDetails/order-details.module.css
> +}
**Надо исправить** 
добавьте, пожалуйста, пустую строку в конце файла, чтобы избавиться от "кирпича" гитхаба.
<img width="135" alt="image" src="https://user-images.githubusercontent.com/45519864/153208476-b69fe4d7-c43f-4051-b2fd-9546e1944fb8.png">

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/App/App.jsx
> +      .then(res => res.json())
**Надо исправить**
согласно заданию, должна быть реализована проверка успешности запроса.
У Вас это не сделано, а сразу (с любым результатом успешным или неуспешным делается res.json(). 
Добавьте, пожалуйста, проверку успешности запроса.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  ingredientsInfo:PropTypes.array.isRequired,
**Надо исправить**
согласно заданию, 
```
Если в качестве пропсов передается объект или массив объектов, 
то в propTypes описана структура этого объекта.
```

Опишите, пожалуйста, этот массив. Документация: https://ru.reactjs.org/docs/typechecking-with-proptypes.html

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  ingridients:PropTypes.array.isRequired,
**Надо исправить**
согласно заданию, 
```
Если в качестве пропсов передается объект или массив объектов, 
то в propTypes описана структура этого объекта.
```

Опишите, пожалуйста, этот массив. Документация: https://ru.reactjs.org/docs/typechecking-with-proptypes.html

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  ingredientsInfo: PropTypes.array.isRequired,
**Надо исправить**
согласно заданию, 
```
Если в качестве пропсов передается объект или массив объектов, 
то в propTypes описана структура этого объекта.
```

Опишите, пожалуйста, этот массив. Документация: https://ru.reactjs.org/docs/typechecking-with-proptypes.html

**Обратите внимание!** 
Такой же аргумент Вы передаете в BurgerConstructor. Это значит, что тип у них будет совпадать. А это значит, что propTypes для этих данных можно создать в отдельном файле src/utils/propTypes.js, например. И импортировать его в обоих компонентах.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    <div className={`${burgerIngredients.card} mt-6 mb-6 ml-3 mr-3`} onClick={addIngrenient}>
**Надо исправить**
для иконки денег используйте, пожалуйста, иконку из UI-библиотеки https://yandex-praktikum.github.io/react-developer-burger-ui-components/docs/icons/#properties

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
>        <img src={img} alt="булка" />
**Надо исправить**
alt неверно отражает описание картинки, т.к. сюда может прийти соус или начинка, а не только булка. Пожалуйста, исправьте этот нюанс так, чтобы в alt было верное содержимое.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            deleteThis={onRemoveItem}
**Надо исправить**
название пропсы deleteThis необходимо подправить. this - является в JS понятием, зарезервированным словом со своим значением. Лучше не использовать его в качестве названия пропсы. Вполне приемлемо назвать пропсу так же onRemoveItem, например,

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            deleteThis={onRemoveItem}
**Надо исправить**
при клике на иконку удаления, кроме верной функциональности удаления ингредиента из конструктора, показывается также модалка с деталями ингредиента. Это неверная функциональность. Пожалуйста, пофиксите.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +export const BurgerConstructor = ({ingredientsInfo, bun, ingridients, onRemoveItem, updateOrderOverlay, updateIngredientOverlay, updateIngredientItem}) => {
**Надо исправить**
несоответствие макету.

 Блок с соусом в конструкторе не вытягивается в ширину.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/45519864/153211317-9d6118b2-80fc-45ba-9ee3-38e536b2f6aa.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/45519864/153211633-82298de6-51ba-4fa3-aeb2-6eee61ed55b2.png">


Дизайн: все добавленные ингредиенты имеют одинаковую ширину.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/45519864/153211418-97315648-3d6b-42b2-b67e-9d3cc69d03cd.png">

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      price += item.price
**Надо исправить**
обратите внимание, что булки у Вас добавляются две (одна сверху, одна снизу), а в стоимость Вы добавляете лишь одну.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/OrderDetails/OrderDetails.jsx
> +export const OrderDetails = ({updateOrderOverlay}) => {
**Надо исправить**
несоответствие макету:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/45519864/153212208-5de2bc43-cb44-4cab-a657-bc75eb4ccb1c.png">

Вокруг иконки галочки у Вас есть некий черный квадрат, чего нет на макете:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/45519864/153212317-52535567-bbc8-4af1-968d-aee24e5c31d2.png">

Проверьте также, можете ли Вы использовать иконки из UI-библиотеки, а не добавлять свой svg: https://yandex-praktikum.github.io/react-developer-burger-ui-components/docs/icons/#properties

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/ModalOverlay/ModalOverlay.jsx
> +    <section className={modalOverlay.overlay}>
**Надо исправить**
section тэг обозначает часть документа. Однако, модалка в данном случае не является таковой. Если Вам нужен лишь контейнер для каких-то данных, то уместнее будет использовать обычный div.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +export const BurgerIngredients = ({ingredientsInfo, updateBun, updateIngridients}) => {
**Надо исправить**
согласно заданию,
```
модальное окно с описанием ингредиента открывается при клике по ингредиенту;
```

У Вас не реализована эта функциональность. По клику по ингредиенту у Вас ингредиент добавляется в конструктор. Исправьте, пожалуйста, функциональность, чтобы выполнить задание.

2022-02-09 13:55 UTC, ChrisGerBy commented on src/components/Modal/Modal.jsx
> +export const Modal = (props) => {
**Надо исправить**
согласно заданию,
```
модальные окна закрываются при клике на крестик, на ModalOverlay или нажатием на клавишу "Esc";
```

У Вас реализована только первая часть (закрытие модалки по клику на крестик). Не реализована функциональность закрытия при клике на ModalOverlay и при нажатии Esc. Пожалуйста, добавьте необходимую функциональность.

2022-02-11 06:53 UTC, ChrisGerBy requested changes
Здравствуйте!
Вы сделали большую работу по рефакторингу! Благодарю Вас за внимание к каждому комментарию. 

Осталось совсем чуть-чуть:
-  уделите, пожалуйста, внимание описанию propTypes и применению переданных пропсов, согласно их типу (Вы описываете один тип (например, массив), а сравниваете массив со строкой - это несоответствие);
- не пренебрегайте точными названиями для функций и переменных. Название функции должно отвечать на вопрос "Что делает функция?", название переменной/аргумента - "Что тут лежит? Какие данные здесь находятся?". Помните, что иногда более длинное название, но точно описывающее содержимое, предпочтительнее, чем короткое. Читая код через год-два-пять, Вы должны понимать сразу, что происходит, а не вникать во всю логику происходящего.

Успехов Вам!

2022-02-11 06:53 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  ingredients: PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.array, PropTypes.string ])).isRequired,
**Надо исправить**
вместо PropTypes.array необходимо указать точный формат данных, согласно заданию 
```
Если в качестве пропсов передается объект или массив объектов, 
то в propTypes описана структура этого объекта.
```

Однако, я рекомендую Вам подумать о рефакторинге кода, чтобы в ingredients приходил всегда один тип данных (массив из строк). 
Массив, содержащий массив id, у Вас появляется при удалении ингредиентов из конструктора. При добавлении - Ваш код чистый и аккуратный, всегда приходит массив строк. Вам стоит посмотреть внимательно свою реализацию функции onRemoveItem в App. Подумайте, как можно применить метод массива filter для рефакторинга этой функции и как сохранить один тип для ingredients.

2022-02-11 06:53 UTC, ChrisGerBy commented on src/components/ElementCreator/ElementCreator.jsx
> +  _id: PropTypes.oneOfType([PropTypes.string, PropTypes.arrayOf(PropTypes.string)]).isRequired,
**Надо исправить**
 в этой компоненте Вы сравниваете `item._id === _id` (item._id по PropTypes должен быть строкой, а _id, согласно Вашему описанию, может быть строкой или массивом строк. Сравнение строки с массивом строк никогда не будет давать true в результате).
Уточните, пожалуйста, можно ли сделать рефакторинг так, чтобы _id принимало лишь один тип данных.
Если же нет, то эту пропсу следует переименовать (например, idsArray или просто ids) и к массиву применять соответствующие методы и не сравнивать со строкой.

2022-02-11 06:53 UTC, ChrisGerBy commented on src/components/Card/Card.jsx
> +  const addIngrenientInList = () => {
**Надо исправить**
пожалуйста, сделайте правку написания названия функции  addIngre **d** ientInList.

2022-02-11 06:53 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +          <CardList array={ingredientsInfo} updateIngredient={updateBun} finding="bun" showIngredientDetailsModal={showIngredientDetailsModal} />
**Можно лучше**
предлагаю Вам сделать следующий рефакторинг:
1. в компоненте BurgerIngredients сделать соответствующую фильтрацию ingredientsInfo по типу finding, который Вы передаете в CardList;
2. в CardList передавать уже конечный массив данных, которые этот CardList  должен отобразить (т.е. в первый CardList передать уже массив булок, во второй - соусы, в третий - начинки), таким образом, Ваш CardList не будет зависеть от всего массива данных и не нужна будет пропса finding. Вы сразу передадите, что же этот CardList должен отобразить, какой массив должен проитерировать.

```
<CardList data={buns} ... />
<CardList data={sauces} ... />
<CardList data={main} ... />
```

Такая организация кода более соответствует подходам React, т.к. логически CardList зависит не от всего массива ингредиентов, а ему нужен только тот массив, который он должен отобразить, все остальное ему не важно.
Плюс сделать фильтрацию Вы можете всего за 1(!) проход по массиву ingredientsInfo, используя метод reduce, например (на данный момент, каждый CardList делает итерацию, т.е. Вы проходите по массиву трижды, вместо одного раза).

2022-02-11 06:53 UTC, ChrisGerBy commented on src/components/OrderDetails/OrderDetails.jsx
> +import { CheckMarkIcon, } from "@ya.praktikum/react-developer-burger-ui-components";
**Надо исправить**
неиспользуемый в компоненте импорт. Либо используйте эту иконку (это наилучший вариант, т.к. в соответствии с заданием необходимо применять иконки из UI-библиотеки), либо удалите импорт.

2022-02-11 06:53 UTC, ChrisGerBy commented on src/components/OrderDetails/OrderDetails.jsx
> +import ReactDOM from "react-dom";
**Надо исправить**
неиспользуемый в компоненте импорт.

2022-02-11 06:53 UTC, ChrisGerBy commented on src/components/App/App.jsx
> +      .then(status)
**Надо исправить**
`status` - это функция и должна называться глаголом, а не существительным (что делает эта функция? **Проверяет** статус, например).

2022-02-11 06:53 UTC, ChrisGerBy commented on src/components/App/App.jsx
> +    return res;
**Можно лучше**
если `res.ok`, то можно сразу возвращать res.json(), а не добавлять еще один then в цепочку обработчиков.

2022-02-11 06:53 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +const priceCalc = (order, array, bun) => {
**Можно лучше**
название аргумента `order` не совсем точно описывает, что туда передается. У Вас там лежат все ингредиенты, кроме булки. По названию же скорее ожидается либо номер заказа, либо все ингредиенты заказа, либо какие-то характеристики заказа. Рекомендую переименовать, чтобы даже через полгода после написания кода, видя эту функцию, Вы понимали, что тут лежит и не надо было вникать в код :) (`notBunIngredients`, `ingredientsWithoutBun`, `saucesAndMain` или что-то вроде того). Лучше название будет длиннее, но понятнее и читабельнее.

2022-02-11 10:14 UTC, ChrisGerBy requested changes
Спасибо за оперативные исправления!
BurgerIngredients стал красивее и читабельнее! Отличная работа!

Почти готово :)

- Еще раз проверьте, пожалуйста, propTypes для пропсы data в CardList. Есть недочет (объявляете один тип - объект со свойствами, а используете для сравнения со строкой).
- Функцию удаления ингредиента из массива НЕОБХОДИМО переписать. В комментарии я подробно расписала, что у Вас выходит сейчас, а что необходимо получить. Не стесняйтесь загуглить возможные решения для случая с добавлением  и удалением из массива различных элементов по id. Возможно, это поможет Вам найти оптимальное решение и сделать ingredients массивом из строк без дополнительных проверок typeof.

Последний рывок!

2022-02-11 10:14 UTC, ChrisGerBy commented on src/components/CardList/CardList.jsx
> +        </p>
**Надо исправить**
`data` у Вас - это объект с ключами name, type и array. Вы же тут делаете проверку на data === String. Ни одно из условий не будет истинным - и в конечном итоге у Вас всегда будет последняя разметка:
```
<p id="main" className="text text_type_main-medium mt-4 mb-6">
          {data.name}
</p>
```

Что рекомендую сделать:
1. универсальную разметку для каждого абзаца
```
<p className="text text_type_main-medium mt-4 mb-6">
          {data.name}
</p>
```
Если есть такие повторяющиеся блоки, то стоит задумываться об их переиспользовании и избегать копи-паста.

2. подкорректировать  верхний и нижний margin так, чтобы и для первого, и для последнего абзаца были верные отступы согласно дизайну
3. убрать у тэга p аттрибут id: на данный момент он не выполняет какой-то необходимой функции для приложения.

2022-02-11 10:14 UTC, ChrisGerBy commented on src/components/OrderDetails/OrderDetails.jsx
> +
**Надо исправить**
уберите, пожалуйста, пустую строку в начале файла.

2022-02-11 10:14 UTC, ChrisGerBy commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  ingredients: PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.string), PropTypes.string ])),
**Надо исправить**
логика работы onRemoveItem в компоненте App все равно пока нуждается в исправлении.

Добавив несколько ингредиентов, а потом удалив, я получаю, что в ingredients лежит некий ингредиент А в двух видах: в виде [ [ingredientA], ingredientA]. При этом первый игнорируется приложением, где Вы передаете его в ElementCreator, а второй (строка) используется `_id={typeof(item) !== 'object'? item: ''}`

<img width="442" alt="image" src="https://user-images.githubusercontent.com/45519864/153570982-5f95f072-5908-485c-8c47-67b3d9153e5a.png">

Зачем же тогда вообще занимать память этим игнорируемым массивом? Это пример плохой реализации функции удаления из массива.

Подумайте, как можно применить метод массива filter для рефакторинга функции onRemoveItem и как сохранить один тип для ingredients, чтобы в нем лежали только актуальный строки id добавленных ингредиентов.  
В итоге у Вас должно получиться так, что ingredients всегда имеет вид  [ 'id1', 'id2', 'id3' ] - массив строк. 

После рефакторинга также удалите везде проверку 
`typeof(item) !== 'object'` в компоненте BurgerConstructor
`typeof(array[0]) === 'object'` в компоненте App.

2022-02-11 10:14 UTC, ChrisGerBy commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const main = {name:'Начинки', type:'main', array:[]}
**Надо исправить**
Вы не используете свойство type объектов bun, sauce, main ни в этой компоненте, ни в CardList, куда передаете в виде пропса.
Это значит, что это лишнее свойство и его можно удалить из объекта.
```
const bun = { name:'Булки', array:[] }
const sauce = { name:'Соусы',  array:[] }
const main = { name:'Начинки',  array:[] }
```

Не забудьте также подправить описание propTypes после удаления этого свойства из объекта.

2022-02-11 10:14 UTC, ChrisGerBy commented on src/components/CardList/CardList.jsx
>  import PropTypes from "prop-types";
**Надо исправить**
уберите, пожалуйста, пустую строку в начале файла.

2022-02-11 13:16 UTC, ChrisGerBy requested changes
Еще одно исправление для onRemoveItem функции необходимо.
Внимательно изучите и разберитесь, как работает метод итерации по массиву filter:
- что он возвращает;
- как работает callback функция, которая в него передается, что она делает с каждым элементом.

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

https://learn.javascript.ru/array-methods#filter

https://medium.com/@stasonmars/%D0%BF%D0%BE%D0%B4%D1%80%D0%BE%D0%B1%D0%BD%D0%BE-%D0%BF%D1%80%D0%BE-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-filter-%D0%B2-javascript-1fcb239a0d74

2022-02-11 13:16 UTC, ChrisGerBy commented on src/components/App/App.jsx
> +    array = array.filter((item)=> typeof(item) === 'string')
**Надо исправить**
при данной реализации у Вас в array всегда будет массив из строк, соответственно, вот эта фильтрация абсолютно лишняя, потому что будет возвращать всегда тот же массив.

Еще одна подсказка:
- у Вас в ingredients лежит [ 'sauceId-1', 'main-id-1', 'main-id-2'];
- в onRemoveItem пришел id  'main-id-2';

сделайте фильтр по массиву ingredients.filter  так, чтобы этот метод вернул новый массив с id-шками, кроме 'main-id-2'.

1. ingredients.filter(callback) будет возвращать всегда новый массив
2. callback - это функция, которая берет каждый элемент массив, делает для него какую-то проверку (element === 'main-id-2', например), если это сравнение даст true, тогда этот element останется в новом финальном массиве, если вернется false - этот element не будет добавлен в финальный массив.

 Я уже Вам написала, пожалуй, все, что можно. Вам осталось избавиться от splice и написать правильно callback функцию :)

2022-02-12 09:15 UTC, ChrisGerBy reviewed
Принимаю работу. Вы проделали большой рефакторинг с первой версии, отправленной на ревью, и до финального результата.

Оставляю Вам, однако, комментарий с тем, как же все-таки просто можно было реализовать удаление элемента из массива. 

Желаю успехов в дальнейшем изучении Реакт!

2022-02-12 09:15 UTC, ChrisGerBy commented on src/components/App/App.jsx
> +    const array = ingredients.filter((item, index)=> index !== deletedIndex)
**Можно лучше**

сдаюсь :)
```
    const array = ingredients.filter((item)=> item !== id)
```

Вот и все, что требовалось. Вам не нужно вычислять индекс айдишки. Вам просто нужно сравнить сам item (элемент массива и есть id) c id, который приходит в onRemoveItem. Экономим ресурсы компа, который делает все эти вычисления - и сразу сравниваем item !== id.

2022-02-13 23:00 UTC, FabioTw commented on src/components/App/App.jsx
> +    const array = ingredients.filter((item, index)=> index !== deletedIndex)
А разве тогда он не будет удалять все одинаковые элементы? Например добавил 3 соуса на одном нажал удаление и удалились все, разве этим методом он останавливается на первом вхождении?

2022-02-15 12:13 UTC, merged